import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from '../lib/sanity'

const watermelonQuery = `*[_type == "watermelon"] {
  _id,
  dateBought,
  purchaseLocation,
  brand,
  image,
  watermelonData
}`

export default function Home({ watermelons }) {
  return (
    <div className={styles.container}>
      {console.log(watermelons)}
      <Head>
        <title>Watermelon Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/watermelon-icon.png" />
      </Head>
    </div>
  )
}

export async function getStaticProps() {
  const watermelons = await sanityClient.fetch(watermelonQuery)
  return { props: { watermelons } }
}
