import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { sanityClient } from '../lib/sanity'
import Table from '../components/table'

const watermelonQuery = `*[_type == "watermelon"] {
  count,
  purchased,
  purchaseLocation,
  origin,
  image,
  sweetScale,
  textureScale,
  rating
}`

export default function Home({ watermelons }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Watermelon Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/watermelon-icon.png" />
        <link rel="stylesheet" href="https://use.typekit.net/hbl5gnh.css" />
      </Head>
      <div className="wrapper">
        <div className="header">
          <img src="/watermelon-metor.svg" alt="Watermelon Metor" />
          <h1>Watermelon Meter</h1>
        </div>
        <Table watermelons={watermelons} />
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const watermelons = await sanityClient.fetch(watermelonQuery)
  return { props: { watermelons } }
}
